[build.environment]
  API_URL = "https://api-tracking.sauravkumal.com.np"
  NODE_VERSION= "16"

[[redirects]]
  from = "/backend/*"
  to = "https://api-tracking.sauravkumal.com.np/:splat"
  status = 200
  force = true
